### ISSUE TITLE
issue-xbrl-attestation.sh

### ISSUE THREAD

**Issue by haroldcarr** [WebOfTrust/keripy#266]
I am trying `./keripy/scripts/demo/vLEI/issue-xbrl-attestation.sh` and get the following results.

Is that what is expected?

```
[nix-shell:~/ws/OLABS/0-next/KERI/keripy]$ source ./scripts/demo/demo-scripts.sh
(keripy) 
[nix-shell:~/ws/OLABS/0-next/KERI/keripy]$ ./scripts/demo/vLEI/issue-xbrl-attestation.sh
KERI Keystore created at: /usr/local/var/keri/ks/external
KERI Database created at: /usr/local/var/keri/db/external
KERI Credential Store created at: /usr/local/var/keri/reg/external

Loading 3 OOBIs...
http://127.0.0.1:5642/oobi/BGKVzj4ve0VSd8z_AmvhLg4lqcC_9WYX90k03q-R_Ydo/controller succeeded
http://127.0.0.1:5643/oobi/BuyRFMideczFZoapylLIyCjSdhtqVb31wZkRKvPfNqkw/controller succeeded
http://127.0.0.1:5644/oobi/Bgoq68HCmYNUDgOz4Skvlu306o_NY-NrYuKAVhk3Zh9c/controller succeeded
Waiting for witness receipts...
Prefix  EWN6BzdXo6IByOsuh_fYanK300iEOrQKf6msmbIeC4Y0
	Public key 1:  DZlaQNStCQzeiMoUONCXr5q8Dnn_XnJb3b1Bwg6cueHg

KERI Keystore created at: /usr/local/var/keri/ks/qvi
KERI Database created at: /usr/local/var/keri/db/qvi
KERI Credential Store created at: /usr/local/var/keri/reg/qvi

Loading 3 OOBIs...
http://127.0.0.1:5642/oobi/BGKVzj4ve0VSd8z_AmvhLg4lqcC_9WYX90k03q-R_Ydo/controller succeeded
http://127.0.0.1:5643/oobi/BuyRFMideczFZoapylLIyCjSdhtqVb31wZkRKvPfNqkw/controller succeeded
http://127.0.0.1:5644/oobi/Bgoq68HCmYNUDgOz4Skvlu306o_NY-NrYuKAVhk3Zh9c/controller succeeded
Waiting for witness receipts...
Prefix  EY4ldIBDZP4Tpnm3RX320BO0yz8Uz2nUSN-C409GnCJM
	Public key 1:  DrwWSrbScuWhhy2K3f-zOakHsTotEjjC50YC2Dh913S4

KERI Keystore created at: /usr/local/var/keri/ks/legal-entity
KERI Database created at: /usr/local/var/keri/db/legal-entity
KERI Credential Store created at: /usr/local/var/keri/reg/legal-entity

Loading 3 OOBIs...
http://127.0.0.1:5643/oobi/BuyRFMideczFZoapylLIyCjSdhtqVb31wZkRKvPfNqkw/controller succeeded
http://127.0.0.1:5644/oobi/Bgoq68HCmYNUDgOz4Skvlu306o_NY-NrYuKAVhk3Zh9c/controller succeeded
http://127.0.0.1:5642/oobi/BGKVzj4ve0VSd8z_AmvhLg4lqcC_9WYX90k03q-R_Ydo/controller succeeded
Waiting for witness receipts...
Prefix  EKXPX7hWw8KK5Y_Mxs2TOuCrGdN45vPIZ78NofRlVBws
	Public key 1:  DsQnKtNPp5RewOThbBZy_9lRPkhU8S16_uDzwKnEP6XY

KERI Keystore created at: /usr/local/var/keri/ks/person
KERI Database created at: /usr/local/var/keri/db/person
KERI Credential Store created at: /usr/local/var/keri/reg/person
	aeid: Bld861UngKEE0jUqmCGzai8QZI_4vHEyAl5YFS6Zik2Y

Loading 3 OOBIs...
http://127.0.0.1:5644/oobi/Bgoq68HCmYNUDgOz4Skvlu306o_NY-NrYuKAVhk3Zh9c/controller succeeded
http://127.0.0.1:5642/oobi/BGKVzj4ve0VSd8z_AmvhLg4lqcC_9WYX90k03q-R_Ydo/controller succeeded
http://127.0.0.1:5643/oobi/BuyRFMideczFZoapylLIyCjSdhtqVb31wZkRKvPfNqkw/controller succeeded
Waiting for witness receipts...
Prefix  Esf8b_AngI1d0KbOFjPGIfpVani0HTagWeaYTLs14PlE
	Public key 1:  DU9FXLRe0yHhcXjxDINny4hXx0NCqRmnrk8nE7SQIDxM

resolving external
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias qvi
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias legal-entity
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias person
resolving qvi
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias external
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias legal-entity
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias person
resolving legal-entity
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias external
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias qvi
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias person
resolving person
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias external
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias qvi
usage: kli [-h] command ...
kli: error: unrecognized arguments: --alias legal-entity
resolving QVI vLEI Schema EWCeT9zTxaZkaC_3-amV2JtG6oUxNA36sCC0P5MI7Buw
http://127.0.0.1:7723/oobi/EWCeT9zTxaZkaC_3-amV2JtG6oUxNA36sCC0P5MI7Buw resolved
http://127.0.0.1:7723/oobi/EWCeT9zTxaZkaC_3-amV2JtG6oUxNA36sCC0P5MI7Buw resolved
http://127.0.0.1:7723/oobi/EWCeT9zTxaZkaC_3-amV2JtG6oUxNA36sCC0P5MI7Buw resolved
http://127.0.0.1:7723/oobi/EWCeT9zTxaZkaC_3-amV2JtG6oUxNA36sCC0P5MI7Buw resolved
resolving Legal Entity vLEI Schema EWJkQCFvKuyxZi582yJPb0wcwuW3VXmFNuvbQuBpgmIs
http://127.0.0.1:7723/oobi/EWJkQCFvKuyxZi582yJPb0wcwuW3VXmFNuvbQuBpgmIs resolved
http://127.0.0.1:7723/oobi/EWJkQCFvKuyxZi582yJPb0wcwuW3VXmFNuvbQuBpgmIs resolved
http://127.0.0.1:7723/oobi/EWJkQCFvKuyxZi582yJPb0wcwuW3VXmFNuvbQuBpgmIs resolved
http://127.0.0.1:7723/oobi/EWJkQCFvKuyxZi582yJPb0wcwuW3VXmFNuvbQuBpgmIs resolved
resolving OOR vLEI Schema E2RzmSCFmG2a5U2OqZF-yUobeSYkW-a3FsN82eZXMxY0
http://127.0.0.1:7723/oobi/E2RzmSCFmG2a5U2OqZF-yUobeSYkW-a3FsN82eZXMxY0 resolved
http://127.0.0.1:7723/oobi/E2RzmSCFmG2a5U2OqZF-yUobeSYkW-a3FsN82eZXMxY0 resolved
http://127.0.0.1:7723/oobi/E2RzmSCFmG2a5U2OqZF-yUobeSYkW-a3FsN82eZXMxY0 resolved
http://127.0.0.1:7723/oobi/E2RzmSCFmG2a5U2OqZF-yUobeSYkW-a3FsN82eZXMxY0 resolved
resolving iXBRL Data Attestation Schema Ehwr6tZh6XakKBKWQW07otQ9uCwg0g7CF-dPz9qb_fwQ
http://127.0.0.1:7723/oobi/Ehwr6tZh6XakKBKWQW07otQ9uCwg0g7CF-dPz9qb_fwQ resolved
http://127.0.0.1:7723/oobi/Ehwr6tZh6XakKBKWQW07otQ9uCwg0g7CF-dPz9qb_fwQ resolved
http://127.0.0.1:7723/oobi/Ehwr6tZh6XakKBKWQW07otQ9uCwg0g7CF-dPz9qb_fwQ resolved
http://127.0.0.1:7723/oobi/Ehwr6tZh6XakKBKWQW07otQ9uCwg0g7CF-dPz9qb_fwQ resolved
Waiting for TEL event witness receipts
Sending TEL events to witnesses
Regsitry:  vLEI-external(ETAbpXRCgLrmv-i0W2ApmojZuljLo6qHhOH9PUWGB2lg) 
	created for Identifier Prefix:  EWN6BzdXo6IByOsuh_fYanK300iEOrQKf6msmbIeC4Y0
Waiting for TEL event witness receipts
Sending TEL events to witnesses
Regsitry:  vLEI-qvi(EowQmtDn4wUc7o57N7w2Hkka3KRoVwR2buo7U8-2kLfo) 
	created for Identifier Prefix:  EY4ldIBDZP4Tpnm3RX320BO0yz8Uz2nUSN-C409GnCJM
Waiting for TEL event witness receipts
Sending TEL events to witnesses
Regsitry:  vLEI-person(EnRuAjHmdPAV1t8AgdbmHGKc9HwDx4_J9BheBvTR9HRM) 
	created for Identifier Prefix:  Esf8b_AngI1d0KbOFjPGIfpVani0HTagWeaYTLs14PlE
Traceback (most recent call last):
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/keripy/bin/kli", line 33, in <module>
    sys.exit(load_entry_point('keri', 'console_scripts', 'kli')())
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/kli.py", line 26, in main
    raise ex
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/kli.py", line 20, in main
    doers = args.handler(args)
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 16, in <lambda>
    parser.set_defaults(handler=lambda args: issueCredential(args),
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 85, in issueCredential
    issueDoer = CredentialIssuer(name=name,
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 145, in __init__
    raise ValueError(f"invalid recipient {recipient}")
ValueError: invalid recipient EY4ldIBDZP4Tpnm3RX320BO0yz8Uz2nUSN-C409GnCJM
Checking mailboxes for any received credentials.....

Current received credentials for qvi (EY4ldIBDZP4Tpnm3RX320BO0yz8Uz2nUSN-C409GnCJM):

Traceback (most recent call last):
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/keripy/bin/kli", line 33, in <module>
    sys.exit(load_entry_point('keri', 'console_scripts', 'kli')())
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/kli.py", line 26, in main
    raise ex
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/kli.py", line 20, in main
    doers = args.handler(args)
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 16, in <lambda>
    parser.set_defaults(handler=lambda args: issueCredential(args),
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 85, in issueCredential
    issueDoer = CredentialIssuer(name=name,
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 145, in __init__
    raise ValueError(f"invalid recipient {recipient}")
ValueError: invalid recipient EKXPX7hWw8KK5Y_Mxs2TOuCrGdN45vPIZ78NofRlVBws
Checking mailboxes for any received credentials.....

Current received credentials for legal-entity (EKXPX7hWw8KK5Y_Mxs2TOuCrGdN45vPIZ78NofRlVBws):

Traceback (most recent call last):
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/keripy/bin/kli", line 33, in <module>
    sys.exit(load_entry_point('keri', 'console_scripts', 'kli')())
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/kli.py", line 26, in main
    raise ex
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/kli.py", line 20, in main
    doers = args.handler(args)
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 16, in <lambda>
    parser.set_defaults(handler=lambda args: issueCredential(args),
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 85, in issueCredential
    issueDoer = CredentialIssuer(name=name,
  File "/Users/hcarr/ws/OLABS/0-next/KERI/keripy/src/keri/app/cli/commands/vc/issue.py", line 145, in __init__
    raise ValueError(f"invalid recipient {recipient}")
ValueError: invalid recipient Esf8b_AngI1d0KbOFjPGIfpVani0HTagWeaYTLs14PlE
Checking mailboxes for any received credentials.....

Current received credentials for person (Esf8b_AngI1d0KbOFjPGIfpVani0HTagWeaYTLs14PlE):

Writing credential E-IQvgnfguEIB8vw_BnX4e08LlpQGHuvJi4QsgCH5oeU to credential.json
Waiting for TEL event witness receipts
Sending TEL events to witnesses
Credential issuance complete, sending to recipient
E-IQvgnfguEIB8vw_BnX4e08LlpQGHuvJi4QsgCH5oeU has been issued.
Current issued credentials for person (Esf8b_AngI1d0KbOFjPGIfpVani0HTagWeaYTLs14PlE):

(keripy) 
[nix-shell:~/ws/OLABS/0-next/KERI/keripy]$ 
```

**Comment by pfeairheller** [comment]
As the readme states in the vLEI directory, those scripts are not thoroughly tested with each push to main.

That being said, someone (@rc-provenant) already let me know out of band that we missed removing the `--alias` parameter to the oobi resolve calls in that script and has offered to submit a PR for fixing it.  I'm going to assign this issue to her so she can close it with her PR.

**Comment by rc-provenant** [comment]
Closed by PR 267
