### ISSUE TITLE
lock no longer works

### ISSUE THREAD

**Issue by rc-provenant** [WebOfTrust/keripy#268]
It returns the following:
2022-08-16 16:34:32 [FALCON] [ERROR] POST /lock => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/Users/ruthchoueka/git/WebOfTrust/keripy/src/keri/app/kiwiing.py", line 64, in on_post
    tcp=self.bootConfig["tcp"],
KeyError: 'tcp'

**Comment by rc-provenant** [comment]
Lock is now working
