### ISSUE TITLE
maturin now seems to be a dependency for installing keripy with pip due to blake3 depending on it

### ISSUE THREAD

**Issue by kentbull** [WebOfTrust/keripy#446]
When installing `keripy` on a fresh Ubuntu container I get an error "No such file or directory: 'maturin'" when running `pip3 install keri`.

The blake3 installation fails with the following error:
```bash
root@02e122fe3811:/# pip3 install keri
Collecting keri
  Using cached keri-0.6.8.tar.gz (350 kB)
  Preparing metadata (setup.py) ... done
Collecting PrettyTable>=3.5.0
  Using cached prettytable-3.6.0-py3-none-any.whl (27 kB)
Collecting PyYaml>=6.0
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (733 kB)
Collecting apispec>=6.0.0
  Using cached apispec-6.0.2-py3-none-any.whl (29 kB)
Collecting blake3>=0.3.1
  Using cached blake3-0.3.3.tar.gz (116 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-g4ivpkts --interpreter /usr/bin/python3`
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-mpfe0zdd/overlay/local/lib/python3.10/dist-packages/maturin/__init__.py", line 174, in prepare_metadata_for_build_wheel
          output = subprocess.check_output(command)
        File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'maturin'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Installing maturin with pip3 resolves the issue:
```bash
$ pip3 install maturin
```

Should `maturin` be added to KERI's dependency list? [Maturin](https://github.com/PyO3/maturin) is a project supporting building Rust crates as Python packages.

**Comment by kentbull** [comment]
I don't think this is relevant anymore.
