### ISSUE TITLE
ERR: 'NoneType' object has no attribute 'accept' while starting witness

### ISSUE THREAD

**Issue by s-a-tanjim** [WebOfTrust/keripy#455]
How to reproduce the error:
```
kli init --name witness --nopasscode --config-dir ${KERI_SCRIPT_DIR} --config-file witness
kli incept --name witness --alias witness --config ${KERI_SCRIPT_DIR} --file ${KERI_DEMO_SCRIPT_DIR}/data/wil-witness-sample.json
kli witness start --name witness --alias witness &
```
If I use `&` at the end(See above), I get the error `ERR: 'NoneType' object has no attribute 'accept'` whenever I create a new witness.

**Comment by s-a-tanjim** [comment]
I tried to remove the keystores using:
`rm -rf /usr/local/var/keri/*` 
And tried to recreate the witness, but still get the same error.

**Comment by psteniusubi** [comment]
Hi. I have seen this error when there is an other process listening on the same TCP port.

Maybe you have left behind a previous "kli witness start" process as you started it in the background with "&"?

**Comment by s-a-tanjim** [comment]
Thank you @psteniusubi. Then I think error message should be improved.

**Comment by m00sey** [comment]
can you edit the issue to reflect your request please

**Comment by daidoji** [comment]
Bug still exists, looks like its in hio but I'm not exactly sure how to handle exceptions that occur so far down the stack as it propagates up to the kli.py exception handler.

_Below run after running equivalent witness command and succeeding_

```
(keri) daidoji@darkstar:~/vLEIDA/Research/sign-demo-1$ DEBUG_KLI=1 kli witness start -H 31337 -T 31338 --name elite-witness --alias elite-witness                           
Traceback (most recent call last):
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/kli.py", line 24, in main
    doers = args.handler(args)
            ^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/commands/witness/start.py", line 19, in <lambda>
    parser.set_defaults(handler=lambda args: launch(args))
                                             ^^^^^^^^^^^^
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/commands/witness/start.py", line 61, in launch
    runWitness(name=args.name,
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/commands/witness/start.py", line 110, in runWitness
    directing.runController(doers=doers, expire=expire)
  File "/home/daidoji/ssi/keripy/src/keri/app/directing.py", line 665, in runController
    doist.do(doers=doers)
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/base/doing.py", line 156, in do
    self.recur()  # increments .tyme runs recur context
    ^^^^^^^^^^^^
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/base/doing.py", line 275, in recur
    tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
           ^^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/base/doing.py", line 568, in do
    self.done = self.recur(tyme=tyme)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/core/tcp/serving.py", line 1071, in recur
    self.server.service()
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/core/tcp/serving.py", line 414, in service
    self.serviceConnects()
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/core/tcp/serving.py", line 292, in serviceConnects
    self.serviceAxes()
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/core/tcp/serving.py", line 269, in serviceAxes
    self.serviceAccepts()  # populate .axes
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/core/tcp/serving.py", line 196, in serviceAccepts
    cs, ca = self.accept()
             ^^^^^^^^^^^^^
  File "/home/daidoji/.pyenv/versions/keri/lib/python3.11/site-packages/hio/core/tcp/serving.py", line 182, in accept
    cs, ca = self.ss.accept()  # virtual connection (socket, host address)
             ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'accept'
```

**Comment by psteniusubi** [comment]
Hi @daidoji 
Here's a simple solution that avoids changes to the hio component.
Implement a catch errors early strategy by adding a test with `server.reopen` to see if this process can bind to the tcp port 

```
$ git diff -- src/keri/app/indirecting.py
diff --git a/src/keri/app/indirecting.py b/src/keri/app/indirecting.py
index d1b482d7..6c449e48 100644
--- a/src/keri/app/indirecting.py
+++ b/src/keri/app/indirecting.py
@@ -88,6 +88,8 @@ def setupWitness(hby, alias="witness", mbx=None, aids=None, tcpPort=5631, httpPo
     app.add_route("/receipts", receiptEnd)

     server = createHttpServer(httpPort, app, keypath, certpath, cafilepath)
+    if not server.reopen():
+        raise RuntimeError(f"cannot create http server on port {httpPort}")
     httpServerDoer = http.ServerDoer(server=server)

     # setup doers
```

In addition you can enable logging at ERROR level. Then you will also see this

```
keri: Error binding server listen socket.
[Errno 98] Address already in use
```
