### ISSUE TITLE
When exporting a vc from kli that doesn't exist we get the error 'ERR: 'Namespace' object has no attribute 'edge''

### ISSUE THREAD

**Issue by daidoji** [WebOfTrust/keripy#664]
##Description
When attempting to export a VC that doesn't exist we get the error `ERR: 'Namespace' object has no attribute 'edge'` which seems unrelated to that credential not existing.

To reproduce:
1.  run the current `./scripts/demo/test-scripts.sh`
2. `kli vc list --name cha1 --verbose # we can see that credentials don't exist`
3. `kli vc export --name cha1 --alias cha1 --said EPWuCVen3-PsX7dcdR5KwTLVsCj44gDreoTwvAaE_xOM # we query the AID of cha1 itself which obviously won't be a match with any credential`

and we'll get the error above.  Changing the `--said` parameter to any value for a credential that doesn't exist seems to give the same error.  

##Reproduction log:
```bash
************************************
Running challenge.sh
************************************
KERI Keystore created at: /home/daidoji/.keri/ks/cha1
KERI Database created at: /home/daidoji/.keri/db/cha1
KERI Credential Store created at: /home/daidoji/.keri/reg/cha1

Loading 3 OOBIs...
http://127.0.0.1:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller succeeded
http://127.0.0.1:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller succeeded
http://127.0.0.1:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller succeeded
Waiting for witness receipts...
Prefix  EIuEcJ_v-A5gHjXrBBhIpzHI4kiduFfVztufqqBHf5YG
        Public key 1:  DN8PnOtgIqSNrQz8GBaDCLIrW2zv75qZRpQrHF2kU428

End role authorization added for role mailbox
(keri) daidoji@LAPTOP-5KEUASIG:~/ssi/keripy$ kli vc list --name cha1 --verbose
Current received credentials for cha1 (EIuEcJ_v-A5gHjXrBBhIpzHI4kiduFfVztufqqBHf5YG):

(keri) daidoji@LAPTOP-5KEUASIG:~/ssi/keripy$ kli vc export --name cha1 --alias cha1 --said EPWuCVen3-PsX7dcdR5KwTLVsCj44gDreoTwvAaE_xOM
ERR: 'Namespace' object has no attribute 'edge'
(keri) daidoji@LAPTOP-5KEUASIG:~/ssi/keripy$ DEBUG_KLI=1 kli vc export --name cha1 --alias cha1 --said EPWuCVen3-PsX7dcdR5KwTLVsCj44gDreoTwvAaE_xO
Traceback (most recent call last):
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/kli.py", line 24, in main
    doers = args.handler(args)
            ^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/commands/vc/export.py", line 20, in <lambda>
    parser.set_defaults(handler=lambda args: export_credentials(args),
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/commands/vc/export.py", line 46, in export_credentials
    chains = args.edge if args.edge is not None else {}
                          ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'edge'
```

## Suggested fix 
Return an error that more correctly reflects the fact that the SAID doesn't exist rather than the attribute error message that seems to reflect the fact that there's some issue with edges in the credential.

**Comment by pfeairheller** [comment]
Fixed with #675
