### ISSUE TITLE
kli watcher start currently erroring out 

### ISSUE THREAD

**Issue by daidoji** [WebOfTrust/keripy#716]
~Tried to start a watcher just to see how it worked and ran into this bug.~

```bash
(keri) daidoji@LAPTOP-5KEUASIG:~/ssi/keripy$ rm -r ~/.keri/
(keri) daidoji@LAPTOP-5KEUASIG:~/ssi/keripy$ DEBUG_KLI=1 kli watcher start --alias foo
Traceback (most recent call last):
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/kli.py", line 24, in main
    doers = args.handler(args)
            ^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/commands/watcher/start.py", line 17, in <lambda>
    parser.set_defaults(handler=lambda args: startWatcher(args))
                                             ^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/commands/watcher/start.py", line 48, in startWatcher
    doers = setupWatcher(name, controller=args.controller, alias=args.alias, base=args.base, bran=args.bran,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daidoji/ssi/keripy/src/keri/app/cli/commands/watcher/start.py", line 67, in setupWatcher
    httpEnd = indirecting.HttpEnd(hab=hab, app=app, rep=rep, mbx=mbx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HttpEnd.__init__() got an unexpected keyword argument 'hab'
```

~Seems like a refactoring issue on HttpEnd.~

Remove kli watcher command per Phil's comment below.

**Comment by pfeairheller** [comment]
That command should be removed.  It never progressed past a "work in progress".

**Comment by daidoji** [comment]
Command removed from keripy
